import * as THREE from "three";

const chapters=[
 {key:"perfil",title:"Quem sou",heading:"PERFIL",content:`<div class="editor-lines" aria-label="Perfil em formato de código"><div class="editor-line"><span class="line-number">01</span><code><span class="syntax-key">const</span> enrico = {</code></div><div class="editor-line editor-indent"><span class="line-number">02</span><code>nome: <span class="syntax-string">"Enrico Lima Freitas"</span>,</code></div><div class="editor-line editor-indent"><span class="line-number">03</span><code>atuacao: <span class="syntax-string">"Suporte &amp; Infraestrutura"</span>,</code></div><div class="editor-line editor-indent"><span class="line-number">04</span><code>estudando: <span class="syntax-string">"Cybersecurity"</span>,</code></div><div class="editor-line editor-indent"><span class="line-number">05</span><code>formacao: <span class="syntax-string">"Desenvolvimento de Sistemas"</span>,</code></div><div class="editor-line editor-indent"><span class="line-number">06</span><code>interesse: <span class="syntax-string">"entender, resolver, construir"</span></code></div><div class="editor-line"><span class="line-number">07</span><code>};</code></div></div><p class="content-note">Trabalho com tecnologia no dia a dia e sigo ampliando minha prática em desenvolvimento e segurança. Meu ponto de partida é sempre entender o problema por inteiro.</p><div class="inline-links"><a class="inline-link" href="https://github.com/Enrico099" target="_blank" rel="noopener">GITHUB <span>↗</span></a><a class="inline-link" href="https://www.linkedin.com/in/enrico-lima-a67021219" target="_blank" rel="noopener">LINKEDIN <span>↗</span></a></div>`},
 {key:"sobre",title:"Sobre mim",heading:"TRAJETÓRIA",content:`<div class="editor-lines" aria-label="Resumo da trajetória"><div class="editor-line"><span class="line-number">01</span><code><span class="syntax-key">const</span> caminho = [</code></div><div class="editor-line editor-indent"><span class="line-number">02</span><code><span class="syntax-string">"Técnico em Desenvolvimento de Sistemas · ETEC"</span>,</code></div><div class="editor-line editor-indent"><span class="line-number">03</span><code><span class="syntax-string">"Desenvolvimento de Sistemas · Fatec"</span>,</code></div><div class="editor-line editor-indent"><span class="line-number">04</span><code><span class="syntax-string">"Cybersecurity · USCS"</span></code></div><div class="editor-line"><span class="line-number">05</span><code>];</code></div></div><p class="content-note">Atuo com suporte e infraestrutura na BGF Consultoria, incluindo atualizações de aplicações e manipulação de dados. Experiências em service desk, atendimento e moderação me ensinaram a olhar para tecnologia também pelo lado de quem usa.</p><p class="content-note">Desde 2018, lidero equipes voluntárias no Amigos do Bem, organizando ações de arrecadação de alimentos.</p>`},
 {key:"experiencia",title:"Experiência",heading:"NO CAMPO",content:`<ol class="experience-list"><li class="experience-item"><time class="experience-date">DEZ/2025 — ATUAL</time><div><h2>Suporte e Infraestrutura <span>@ BGF Consultoria</span></h2><p>Suporte, infraestrutura, atualizações de aplicações e manipulação de dados.</p></div></li><li class="experience-item"><time class="experience-date">AGO/2024 — FEV/2025</time><div><h2>T.I. — Service Desk <span>@ HS Prevent</span></h2><p>Resolução de problemas dos sistemas internos utilizados pela empresa.</p></div></li><li class="experience-item"><time class="experience-date">MAR/2024 — MAR/2025</time><div><h2>Moderador de Conteúdo <span>@ East River</span></h2><p>Análise de propagandas para exibição em plataformas digitais.</p></div></li><li class="experience-item"><time class="experience-date">ABR/2024 — JUL/2024</time><div><h2>Suporte ao Cliente <span>@ Contax · Cartão Ticket</span></h2><p>Atendimento de transações, bloqueios, emissões, saldo e recargas.</p></div></li><li class="experience-item"><time class="experience-date">MAI/2018 — ATUAL</time><div><h2>Líder de Equipe voluntário <span>@ Amigos do Bem</span></h2><p>Organização de voluntários para arrecadação de alimentos.</p></div></li></ol>`},
 {key:"projetos",title:"Projetos",heading:"EM CONSTRUÇÃO",content:`<div class="project-list"><article class="project-card"><div class="project-art project-art-finance"><div class="art-label"><small>01 / INTELIGÊNCIA ECONÔMICA</small><strong>Coleta + análise</strong><span>YAHOO · BCB · NOTÍCIAS</span></div></div><div class="project-card-body"><div class="project-card-meta"><span>BOT + DASHBOARD</span><a href="https://github.com/Enrico099/Coleta-de-dados-financeiros" target="_blank" rel="noopener">CÓDIGO ↗</a></div><h2>Bot de Inteligência Econômica</h2><p>Coleta cotações, indicadores do Banco Central, notícias e posts. Analisa tendências e sentimento, com dashboard, alertas e resumos via Telegram e e-mail.</p><ul class="project-tags"><li>Python</li><li>Streamlit</li><li>SQLAlchemy</li><li>Plotly</li></ul></div></article><article class="project-card"><div class="project-art"><div class="art-label"><small>02 / CATÁLOGO</small><strong>MotoHub</strong><span>MULTI-LOJA · JWT · WEBP</span></div></div><div class="project-card-body"><div class="project-card-meta"><span>COMÉRCIO DIGITAL</span><a href="https://github.com/Enrico099/lojamotos" target="_blank" rel="noopener">CÓDIGO ↗</a></div><h2>MotoHub — Loja de Motos</h2><p>Plataforma SaaS de catálogo para concessionárias, com arquitetura multi-loja, autenticação JWT e otimização de imagens.</p><ul class="project-tags"><li>Node.js</li><li>MySQL</li><li>Prisma</li><li>Docker</li></ul></div></article><article class="project-card"><div class="project-art project-art-upa"><div class="art-label"><small>03 / SAÚDE</small><strong>Cadastro UPA</strong><span>REGISTRO · CONSULTA</span></div></div><div class="project-card-body"><div class="project-card-meta"><span>GESTÃO DE ATENDIMENTO</span><a href="https://github.com/Enrico099/ubs-repo" target="_blank" rel="noopener">CÓDIGO ↗</a></div><h2>Cadastro de Pacientes</h2><p>Sistema web para registrar e consultar atendimentos, com frontend e backend separados.</p><ul class="project-tags"><li>HTML</li><li>CSS</li><li>JavaScript</li><li>Backend</li></ul></div></article><article class="project-card"><div class="project-art project-art-padaria"><div class="art-label"><small>04 / VAREJO</small><strong>Padaria</strong><span>VITE · SUPABASE</span></div></div><div class="project-card-body"><div class="project-card-meta"><span>CATÁLOGO WEB</span><a href="https://github.com/Enrico099/Padaria" target="_blank" rel="noopener">CÓDIGO ↗</a></div><h2>Padaria</h2><p>Aplicação web para uma padaria, com frontend em TypeScript e dados gerenciados na nuvem.</p><ul class="project-tags"><li>TypeScript</li><li>Vite</li><li>Tailwind</li><li>Supabase</li></ul></div></article></div>`},
 {key:"stack",title:"Stack",heading:"FERRAMENTAS",content:`<div class="skill-groups"><section class="skill-group"><h2>Linguagens <span>01</span></h2><div class="skill-tags"><span>Java</span><span>Python</span><span>C</span><span>JavaScript</span><span>TypeScript</span><span>HTML &amp; CSS</span></div></section><section class="skill-group"><h2>Dados <span>02</span></h2><div class="skill-tags"><span>SQL</span><span>MySQL</span><span>Prisma ORM</span><span>Supabase</span><span>Modelagem</span></div></section><section class="skill-group"><h2>Infra &amp; Cloud <span>03</span></h2><div class="skill-tags"><span>AWS</span><span>Docker</span><span>Node.js</span><span>Git &amp; GitHub</span><span>Linux</span></div></section><section class="skill-group"><h2>Suporte &amp; Segurança <span>04</span></h2><div class="skill-tags"><span>Service Desk</span><span>Troubleshooting</span><span>Atendimento</span><span>Cybersecurity</span><span>Liderança</span></div></section></div><p class="content-note">Ferramentas que fazem parte dos meus estudos e projetos. A lista acompanha o que estou praticando, não uma escala de proficiência.</p>`},
 {key:"formacao",title:"Formação",heading:"APRENDIZADO CONTÍNUO",content:`<div class="education-list"><article class="education-item"><time>2025 — 2029</time><div><h2>Cybersecurity</h2><p>Universidade de São Caetano do Sul (USCS)</p></div></article><article class="education-item"><time>2024 — 2025</time><div><h2>Desenvolvimento de Sistemas</h2><p>Fatec</p></div></article><article class="education-item"><time>2021 — 2023</time><div><h2>Técnico em Desenvolvimento de Sistemas</h2><p>ETEC</p></div></article><article class="education-item"><time>CERTIFICAÇÃO</time><div><h2>AWS Certified</h2><p>Amazon Web Services</p></div></article></div>`},
 {key:"contato",title:"Contato",heading:"PRÓXIMA CONVERSA",content:`<div class="contact-layout"><p>Estou aberto a conversar sobre oportunidades em desenvolvimento, infraestrutura e segurança da informação. Se algum projeto chamou sua atenção, vamos trocar uma ideia.</p><div class="contact-actions"><a class="contact-action" href="mailto:enricolimafreitas@gmail.com">ENVIAR E-MAIL <span>↗</span></a><a class="contact-action" href="https://www.linkedin.com/in/enrico-lima-a67021219" target="_blank" rel="noopener">LINKEDIN <span>↗</span></a></div></div>`}
];
chapters[0].content=chapters[0].content.replace("Trabalho com tecnologia no dia a dia e sigo ampliando minha prática em desenvolvimento e segurança.","Sou desenvolvedor de sistemas em formação e também atuo profissionalmente com suporte e infraestrutura. Desenvolvo aplicações enquanto aprofundo meus estudos em cybersecurity.");

const chapterContent=document.querySelector("#chapterContent"),chapterPath=document.querySelector("#chapterPath"),chapterIndex=document.querySelector("#chapterIndex"),chapterTitle=document.querySelector("#chapterTitle"),chapterCount=document.querySelector("#chapterCount"),chapterPicker=document.querySelector("#chapterPicker"),chapterMenu=document.querySelector("#chapterMenu"),pickerNumber=document.querySelector("#pickerNumber"),pickerTitle=document.querySelector("#pickerTitle"),pickerTotal=document.querySelector("#pickerTotal"),previousButton=document.querySelector("#previousChapter"),nextButton=document.querySelector("#nextChapter"),panel=document.querySelector(".chapter-window");
let activeChapter=0;
const renderChapterMenu=()=>{chapterMenu.innerHTML=chapters.map((chapter,index)=>`<button class="chapter-option" type="button" role="option" data-chapter="${index}" aria-selected="${index===activeChapter}"><span>${String(index+1).padStart(2,"0")}</span><span>${chapter.title}</span><span>${chapter.heading}</span></button>`).join("")};
const showChapter=(index)=>{activeChapter=Math.max(0,Math.min(chapters.length-1,index));const chapter=chapters[activeChapter],number=String(activeChapter+1).padStart(2,"0");chapterPath.textContent=`${chapter.key}.json`;chapterIndex.textContent=`${number} / ${chapter.heading}`;chapterTitle.textContent=chapter.title;chapterCount.innerHTML=`${number} <i>/</i> ${String(chapters.length).padStart(2,"0")}`;chapterContent.innerHTML=chapter.content;chapterContent.scrollTop=0;pickerNumber.textContent=number;pickerTitle.textContent=chapter.heading;pickerTotal.textContent=`${activeChapter+1} / ${chapters.length}`;previousButton.disabled=activeChapter===0;nextButton.disabled=activeChapter===chapters.length-1;renderChapterMenu()};
const setMenuOpen=(open)=>{chapterMenu.hidden=!open;chapterPicker.setAttribute("aria-expanded",String(open));chapterPicker.querySelector(".picker-chevron").textContent=open?"⌄":"⌃"};
chapterPicker.addEventListener("click",()=>setMenuOpen(chapterMenu.hidden));chapterMenu.addEventListener("click",(event)=>{const option=event.target.closest("[data-chapter]");if(!option)return;showChapter(Number(option.dataset.chapter));setMenuOpen(false);chapterPicker.focus()});previousButton.addEventListener("click",()=>showChapter(activeChapter-1));nextButton.addEventListener("click",()=>showChapter(activeChapter+1));
document.querySelector("#expandPanel").addEventListener("click",(event)=>{const expanded=panel.classList.toggle("is-expanded");event.currentTarget.setAttribute("aria-expanded",String(expanded));event.currentTarget.setAttribute("aria-label",expanded?"Recolher painel":"Expandir painel");event.currentTarget.querySelector("span").textContent=expanded?"recolher":"expandir"});
document.addEventListener("keydown",(event)=>{if(event.key==="Escape"){setMenuOpen(false);if(panel.classList.contains("is-expanded")){panel.classList.remove("is-expanded");const button=document.querySelector("#expandPanel");button.setAttribute("aria-expanded","false");button.setAttribute("aria-label","Expandir painel");button.querySelector("span").textContent="expandir"}return}if(event.altKey||event.ctrlKey||event.metaKey||/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;if(event.key==="ArrowLeft")showChapter(activeChapter-1);if(event.key==="ArrowRight")showChapter(activeChapter+1);if(event.key==="Home")showChapter(0);if(event.key==="End")showChapter(chapters.length-1)});
document.addEventListener("click",(event)=>{if(!chapterMenu.hidden&&!chapterMenu.contains(event.target)&&!chapterPicker.contains(event.target))setMenuOpen(false)});showChapter(0);
const projectShotsObserver=new MutationObserver(()=>{const artwork=chapterContent.querySelector(".project-card:nth-child(2) .project-art");if(!artwork||artwork.querySelector(".project-shots"))return;artwork.removeAttribute("aria-hidden");artwork.classList.add("has-screenshots");artwork.insertAdjacentHTML("beforeend",`<div class="project-shots"><a href="./motohub-dashboard.png" target="_blank" rel="noopener"><img src="./motohub-dashboard.png" alt="Painel MotoHub com o anúncio Honda CG 160 Titan 2022 cadastrado"><span>Painel da loja ↗</span></a><a href="./motohub-storefront.png" target="_blank" rel="noopener"><img src="./motohub-storefront.png" alt="Vitrine pública MotoHub com a Honda CG 160 Titan 2022"><span>Vitrine pública ↗</span></a></div>`)});
projectShotsObserver.observe(chapterContent,{childList:true});

const canvas=document.querySelector("#cityScene"),reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)"),pointer={x:0,y:0};let renderer,animationFrame=0;
try{
 renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x111612);scene.fog=new THREE.Fog(0x111612,15,47);
 const camera=new THREE.PerspectiveCamera(47,1,.1,100);camera.position.set(0,4.3,10.6);camera.lookAt(0,1.7,-3.8);scene.add(new THREE.HemisphereLight(0xc4d9c1,0x24271e,2.1));
 const keyLight=new THREE.DirectionalLight(0xffd5a0,3.2);keyLight.position.set(-4,9,6);scene.add(keyLight);const greenLight=new THREE.PointLight(0xb9f36b,20,15);greenLight.position.set(4,4,-2);scene.add(greenLight);const warmLight=new THREE.PointLight(0xef9261,17,18);warmLight.position.set(-5,3,-8);scene.add(warmLight);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,90),new THREE.MeshStandardMaterial({color:0x20251e,roughness:.94,metalness:.06}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-.04,-15);scene.add(floor);const road=new THREE.Mesh(new THREE.PlaneGeometry(8.6,74),new THREE.MeshStandardMaterial({color:0x171b18,roughness:.87}));road.rotation.x=-Math.PI/2;road.position.set(0,0,-17);scene.add(road);
 const laneMaterial=new THREE.MeshBasicMaterial({color:0x9ba18c,transparent:true,opacity:.43});for(let markerIndex=0;markerIndex<17;markerIndex+=1){const marker=new THREE.Mesh(new THREE.PlaneGeometry(.075,1.3),laneMaterial);marker.rotation.x=-Math.PI/2;marker.position.set(0,.012,5-markerIndex*4.1);scene.add(marker)}
 const sidewalkMaterial=new THREE.MeshStandardMaterial({color:0x34372c,roughness:.9});for(const side of [-1,1]){const sidewalk=new THREE.Mesh(new THREE.BoxGeometry(1.15,.17,76),sidewalkMaterial);sidewalk.position.set(side*4.9,.05,-17);scene.add(sidewalk)}
 const buildingColors=[0x28322a,0x34342b,0x263332,0x3a3028,0x252c27],windowColors=[0xd5c17b,0xb9d27b,0xe19a68,0x749e87];let seed=73;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};const materialCache=new Map();const getMaterial=(color)=>{if(!materialCache.has(color))materialCache.set(color,new THREE.MeshStandardMaterial({color,roughness:.8,metalness:.12}));return materialCache.get(color)};
 for(let buildingIndex=0;buildingIndex<26;buildingIndex+=1){for(const side of [-1,1]){const width=2.2+random()*2.4,depth=2.5+random()*2.6,height=4.5+random()*11,building=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(width,height,depth),getMaterial(buildingColors[Math.floor(random()*buildingColors.length)]));body.position.y=height/2;building.add(body);const facadeOffset=width/2+.012,windowRows=Math.max(2,Math.floor(height/1.55));for(let row=0;row<windowRows;row+=1){for(let column=0;column<2;column+=1){if(random()<.22)continue;const paneColor=windowColors[Math.floor(random()*windowColors.length)],pane=new THREE.Mesh(new THREE.PlaneGeometry(.24,.42),new THREE.MeshBasicMaterial({color:paneColor,transparent:true,opacity:.83}));pane.position.set(side===-1?facadeOffset:-facadeOffset,1+row*1.35,(column-.5)*(depth*.36));pane.rotation.y=side===-1?Math.PI/2:-Math.PI/2;building.add(pane)}}building.position.set(side*(5.65+random()*2.2),0,3-buildingIndex*2.55);building.rotation.y=(random()-.5)*.08;scene.add(building)}}
 const lampMetal=new THREE.MeshStandardMaterial({color:0x46483b,roughness:.65,metalness:.45}),lampLight=new THREE.MeshBasicMaterial({color:0xf0bd70});for(let lampIndex=0;lampIndex<7;lampIndex+=1){for(const side of [-1,1]){const lamp=new THREE.Group(),pole=new THREE.Mesh(new THREE.CylinderGeometry(.035,.055,3.4,6),lampMetal);pole.position.y=1.7;lamp.add(pole);const arm=new THREE.Mesh(new THREE.BoxGeometry(.55,.045,.045),lampMetal);arm.position.set(-side*.23,3.36,0);lamp.add(arm);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.105,8,6),lampLight);bulb.position.set(-side*.47,3.28,0);lamp.add(bulb);lamp.position.set(side*4.5,0,1-lampIndex*8.4);scene.add(lamp)}}
 const person=new THREE.Group(),jacket=new THREE.MeshStandardMaterial({color:0x9cc85b,roughness:.75}),trousers=new THREE.MeshStandardMaterial({color:0x252b26,roughness:.9}),skin=new THREE.MeshStandardMaterial({color:0xb88766,roughness:.9}),shoes=new THREE.MeshStandardMaterial({color:0xd7d8c6,roughness:.9}),hairMaterial=new THREE.MeshStandardMaterial({color:0x25221e,roughness:.95});const torso=new THREE.Mesh(new THREE.CylinderGeometry(.39,.47,1.08,9),jacket);torso.position.y=1.52;person.add(torso);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.11,.12,.19,8),skin);neck.position.y=2.16;person.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.26,12,10),skin);head.position.set(0,2.48,0);person.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.267,12,8,0,Math.PI*2,0,Math.PI*.54),hairMaterial);hair.position.set(0,2.53,-.015);person.add(hair);const backpack=new THREE.Mesh(new THREE.BoxGeometry(.57,.67,.24),new THREE.MeshStandardMaterial({color:0x343d30,roughness:.95}));backpack.position.set(0,1.61,-.31);person.add(backpack);
 for(const side of [-1,1]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.105,.09,.82,7),jacket);arm.position.set(side*.48,1.58,.015);arm.rotation.z=side*-.12;person.add(arm);const hand=new THREE.Mesh(new THREE.SphereGeometry(.105,8,6),skin);hand.position.set(side*.53,1.13,.025);person.add(hand);const leg=new THREE.Mesh(new THREE.CylinderGeometry(.14,.105,.78,7),trousers);leg.position.set(side*.2,.49,0);person.add(leg);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.24,.14,.39),shoes);shoe.position.set(side*.2,.1,.08);person.add(shoe)}const stripe=new THREE.Mesh(new THREE.BoxGeometry(.045,.9,.015),new THREE.MeshBasicMaterial({color:0x213021}));stripe.position.set(-.08,1.52,.405);person.add(stripe);person.position.set(-.65,0,-2.2);scene.add(person);
 const terminal=new THREE.Group(),terminalFrame=new THREE.Mesh(new THREE.BoxGeometry(1.12,1.48,.075),new THREE.MeshStandardMaterial({color:0x263128,emissive:0x263128,emissiveIntensity:.24,metalness:.5,roughness:.35}));terminalFrame.position.y=1.55;terminal.add(terminalFrame);const screen=new THREE.Mesh(new THREE.PlaneGeometry(.94,1.27),new THREE.MeshBasicMaterial({color:0x9dcf68}));screen.position.set(0,1.56,.043);terminal.add(screen);const terminalBase=new THREE.Mesh(new THREE.BoxGeometry(.88,.11,.48),lampMetal);terminalBase.position.set(0,.79,.1);terminal.add(terminalBase);const screenMark=new THREE.Mesh(new THREE.BoxGeometry(.34,.08,.012),new THREE.MeshBasicMaterial({color:0x273427}));screenMark.position.set(-.15,1.98,.054);terminal.add(screenMark);terminal.position.set(2.35,0,-2.8);terminal.rotation.y=-.16;scene.add(terminal);
 person.position.set(-1.45,0,.45);person.scale.setScalar(1.35);terminal.position.set(2.25,0,.35);
 const origin=new THREE.Vector3(0,4.3,10.6),target=new THREE.Vector3(0,-1,-3.8);const render=(time=0)=>{const elapsed=time*.001;camera.position.x+=(origin.x+(reducedMotion.matches?0:pointer.x)*.42-camera.position.x)*.025;camera.position.y+=(origin.y-(reducedMotion.matches?0:pointer.y)*.2-camera.position.y)*.025;camera.lookAt(target.x+(reducedMotion.matches?0:pointer.x)*.36,target.y-(reducedMotion.matches?0:pointer.y)*.14,target.z);if(!reducedMotion.matches){person.position.y=Math.sin(elapsed*1.3)*.025;terminal.rotation.y=-.16+Math.sin(elapsed*.42)*.035}renderer.render(scene,camera)};const resize=()=>{const width=window.innerWidth,height=window.innerHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.fov=width<600?54:width<900?50:47;camera.updateProjectionMatrix();render()};window.addEventListener("resize",resize);window.addEventListener("pointermove",(event)=>{pointer.x=event.clientX/window.innerWidth*2-1;pointer.y=event.clientY/window.innerHeight*2-1},{passive:true});resize();if(!reducedMotion.matches){const animate=(time)=>{render(time);animationFrame=window.requestAnimationFrame(animate)};animationFrame=window.requestAnimationFrame(animate)}
}catch(error){canvas.setAttribute("aria-label","Fundo 3D indisponível. O conteúdo e os controles do portfólio continuam acessíveis.");console.error("Não foi possível inicializar a cena 3D do portfólio.",error)}
window.addEventListener("pagehide",()=>{if(animationFrame)window.cancelAnimationFrame(animationFrame);renderer?.dispose()});
